package com.chmsu.heis.model.documentTracker;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.File;
import java.sql.Date;

@Data
@NoArgsConstructor
@Entity
public class DocumentTrackerDocument {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long documentId;

    private Long documentNumber;
    private String subject;
    private Date dateOfLetter;
    private Long documentType;
    private Long fromUserId; // Changed 'from' to 'fromUserId' to avoid conflict with Java keyword
    private Date date;
    private Date time;
    private Long numberOfPages;
    private File attachedFile;
    //private String status;
    private String printStatus;

    // Constructors, getters, and setters are automatically generated by Lombok
}

